language: node_js
node_js:
    - 12

services:
    - docker 

jobs:
    include:
    - stage: Check code quality
      install:
        - npm install --global prettier
      script:
        - prettier --check "src/**/*.js"

    - stage: Build & push Docker image
      script:
        - docker build -t wilfreddev/website:latest .
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push wilfreddev/website:latest
        on:
            branch: master

      after_deploy:
        - rm -rf /home/travis/.docker/config.json
